import AuthProvider from '@/components/AuthProvider/AuthProvider';
import Footer from '@/components/footer/footer';
import Nav from '@/components/nav/nav';
import { Inter } from 'next/font/google';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) { 
  return (
    <html>
      <body className={inter.className}>
        <AuthProvider>
        <Nav/>
        <div className='max-w-screen-xl p-4 min-h-screen mx-auto'>

        {children}
        </div>
        <Footer/>
        </AuthProvider>
        </body> 
    </html>
  )
}
